/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as KontakImport } from './routes/kontak'
import { Route as DeferredImport } from './routes/deferred'
import { Route as PathlessLayoutImport } from './routes/_pathlessLayout'
import { Route as TipeMobileRouteImport } from './routes/tipe-mobile.route'
import { Route as InfoPromoRouteImport } from './routes/info-promo.route'
import { Route as AdminRouteImport } from './routes/admin.route'
import { Route as IndexImport } from './routes/index'
import { Route as TipeMobilIndexImport } from './routes/tipe-mobil.index'
import { Route as InfoPromoIndexImport } from './routes/info-promo.index'
import { Route as AdminIndexImport } from './routes/admin.index'
import { Route as TipeMobilModelImport } from './routes/tipe-mobil.$model'
import { Route as InfoPromoSlugImport } from './routes/info-promo.$slug'
import { Route as AdminKontakImport } from './routes/admin.kontak'
import { Route as AdminHomepageImport } from './routes/admin.homepage'
import { Route as AdminContactInfoImport } from './routes/admin.contact-info'
import { Route as PathlessLayoutNestedLayoutImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as AdminModelsRouteImport } from './routes/admin.models.route'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles.route'
import { Route as AdminModelsIndexImport } from './routes/admin.models.index'
import { Route as AdminArticlesIndexImport } from './routes/admin.articles.index'
import { Route as AdminModelsIdImport } from './routes/admin.models.$id'
import { Route as AdminArticlesNewImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdImport } from './routes/admin.articles.$id'
import { Route as PathlessLayoutNestedLayoutRouteBImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteAImport } from './routes/_pathlessLayout/_nested-layout/route-a'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const KontakRoute = KontakImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRoute,
} as any)

const DeferredRoute = DeferredImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRoute,
} as any)

const PathlessLayoutRoute = PathlessLayoutImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRoute,
} as any)

const TipeMobileRouteRoute = TipeMobileRouteImport.update({
  id: '/tipe-mobile',
  path: '/tipe-mobile',
  getParentRoute: () => rootRoute,
} as any)

const InfoPromoRouteRoute = InfoPromoRouteImport.update({
  id: '/info-promo',
  path: '/info-promo',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TipeMobilIndexRoute = TipeMobilIndexImport.update({
  id: '/tipe-mobil/',
  path: '/tipe-mobil/',
  getParentRoute: () => rootRoute,
} as any)

const InfoPromoIndexRoute = InfoPromoIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InfoPromoRouteRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)

const TipeMobilModelRoute = TipeMobilModelImport.update({
  id: '/tipe-mobil/$model',
  path: '/tipe-mobil/$model',
  getParentRoute: () => rootRoute,
} as any)

const InfoPromoSlugRoute = InfoPromoSlugImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InfoPromoRouteRoute,
} as any)

const AdminKontakRoute = AdminKontakImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminHomepageRoute = AdminHomepageImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminContactInfoRoute = AdminContactInfoImport.update({
  id: '/contact-info',
  path: '/contact-info',
  getParentRoute: () => AdminRouteRoute,
} as any)

const PathlessLayoutNestedLayoutRoute = PathlessLayoutNestedLayoutImport.update(
  {
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any,
)

const AdminModelsRouteRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminArticlesRouteRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminModelsIndexRoute = AdminModelsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminModelsRouteRoute,
} as any)

const AdminArticlesIndexRoute = AdminArticlesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminArticlesRouteRoute,
} as any)

const AdminModelsIdRoute = AdminModelsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminModelsRouteRoute,
} as any)

const AdminArticlesNewRoute = AdminArticlesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArticlesRouteRoute,
} as any)

const AdminArticlesIdRoute = AdminArticlesIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminArticlesRouteRoute,
} as any)

const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteAImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/info-promo': {
      id: '/info-promo'
      path: '/info-promo'
      fullPath: '/info-promo'
      preLoaderRoute: typeof InfoPromoRouteImport
      parentRoute: typeof rootRoute
    }
    '/tipe-mobile': {
      id: '/tipe-mobile'
      path: '/tipe-mobile'
      fullPath: '/tipe-mobile'
      preLoaderRoute: typeof TipeMobileRouteImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutImport
      parentRoute: typeof rootRoute
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredImport
      parentRoute: typeof rootRoute
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutImport
      parentRoute: typeof PathlessLayoutImport
    }
    '/admin/contact-info': {
      id: '/admin/contact-info'
      path: '/contact-info'
      fullPath: '/admin/contact-info'
      preLoaderRoute: typeof AdminContactInfoImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/kontak': {
      id: '/admin/kontak'
      path: '/kontak'
      fullPath: '/admin/kontak'
      preLoaderRoute: typeof AdminKontakImport
      parentRoute: typeof AdminRouteImport
    }
    '/info-promo/$slug': {
      id: '/info-promo/$slug'
      path: '/$slug'
      fullPath: '/info-promo/$slug'
      preLoaderRoute: typeof InfoPromoSlugImport
      parentRoute: typeof InfoPromoRouteImport
    }
    '/tipe-mobil/$model': {
      id: '/tipe-mobil/$model'
      path: '/tipe-mobil/$model'
      fullPath: '/tipe-mobil/$model'
      preLoaderRoute: typeof TipeMobilModelImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminRouteImport
    }
    '/info-promo/': {
      id: '/info-promo/'
      path: '/'
      fullPath: '/info-promo/'
      preLoaderRoute: typeof InfoPromoIndexImport
      parentRoute: typeof InfoPromoRouteImport
    }
    '/tipe-mobil/': {
      id: '/tipe-mobil/'
      path: '/tipe-mobil'
      fullPath: '/tipe-mobil'
      preLoaderRoute: typeof TipeMobilIndexImport
      parentRoute: typeof rootRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteAImport
      parentRoute: typeof PathlessLayoutNestedLayoutImport
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBImport
      parentRoute: typeof PathlessLayoutNestedLayoutImport
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdImport
      parentRoute: typeof AdminArticlesRouteImport
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewImport
      parentRoute: typeof AdminArticlesRouteImport
    }
    '/admin/models/$id': {
      id: '/admin/models/$id'
      path: '/$id'
      fullPath: '/admin/models/$id'
      preLoaderRoute: typeof AdminModelsIdImport
      parentRoute: typeof AdminModelsRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexImport
      parentRoute: typeof AdminArticlesRouteImport
    }
    '/admin/models/': {
      id: '/admin/models/'
      path: '/'
      fullPath: '/admin/models/'
      preLoaderRoute: typeof AdminModelsIndexImport
      parentRoute: typeof AdminModelsRouteImport
    }
  }
}

// Create and export the route tree

interface AdminArticlesRouteRouteChildren {
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
}

const AdminArticlesRouteRouteChildren: AdminArticlesRouteRouteChildren = {
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
}

const AdminArticlesRouteRouteWithChildren =
  AdminArticlesRouteRoute._addFileChildren(AdminArticlesRouteRouteChildren)

interface AdminModelsRouteRouteChildren {
  AdminModelsIdRoute: typeof AdminModelsIdRoute
  AdminModelsIndexRoute: typeof AdminModelsIndexRoute
}

const AdminModelsRouteRouteChildren: AdminModelsRouteRouteChildren = {
  AdminModelsIdRoute: AdminModelsIdRoute,
  AdminModelsIndexRoute: AdminModelsIndexRoute,
}

const AdminModelsRouteRouteWithChildren =
  AdminModelsRouteRoute._addFileChildren(AdminModelsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminArticlesRouteRoute: typeof AdminArticlesRouteRouteWithChildren
  AdminModelsRouteRoute: typeof AdminModelsRouteRouteWithChildren
  AdminContactInfoRoute: typeof AdminContactInfoRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminKontakRoute: typeof AdminKontakRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminArticlesRouteRoute: AdminArticlesRouteRouteWithChildren,
  AdminModelsRouteRoute: AdminModelsRouteRouteWithChildren,
  AdminContactInfoRoute: AdminContactInfoRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminKontakRoute: AdminKontakRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface InfoPromoRouteRouteChildren {
  InfoPromoSlugRoute: typeof InfoPromoSlugRoute
  InfoPromoIndexRoute: typeof InfoPromoIndexRoute
}

const InfoPromoRouteRouteChildren: InfoPromoRouteRouteChildren = {
  InfoPromoSlugRoute: InfoPromoSlugRoute,
  InfoPromoIndexRoute: InfoPromoIndexRoute,
}

const InfoPromoRouteRouteWithChildren = InfoPromoRouteRoute._addFileChildren(
  InfoPromoRouteRouteChildren,
)

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/info-promo': typeof InfoPromoRouteRouteWithChildren
  '/tipe-mobile': typeof TipeMobileRouteRoute
  '': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/kontak': typeof KontakRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/articles': typeof AdminArticlesRouteRouteWithChildren
  '/admin/models': typeof AdminModelsRouteRouteWithChildren
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/kontak': typeof AdminKontakRoute
  '/info-promo/$slug': typeof InfoPromoSlugRoute
  '/tipe-mobil/$model': typeof TipeMobilModelRoute
  '/admin/': typeof AdminIndexRoute
  '/info-promo/': typeof InfoPromoIndexRoute
  '/tipe-mobil': typeof TipeMobilIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/models/$id': typeof AdminModelsIdRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/models/': typeof AdminModelsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tipe-mobile': typeof TipeMobileRouteRoute
  '': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/kontak': typeof KontakRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/kontak': typeof AdminKontakRoute
  '/info-promo/$slug': typeof InfoPromoSlugRoute
  '/tipe-mobil/$model': typeof TipeMobilModelRoute
  '/admin': typeof AdminIndexRoute
  '/info-promo': typeof InfoPromoIndexRoute
  '/tipe-mobil': typeof TipeMobilIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/models/$id': typeof AdminModelsIdRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/models': typeof AdminModelsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/info-promo': typeof InfoPromoRouteRouteWithChildren
  '/tipe-mobile': typeof TipeMobileRouteRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/kontak': typeof KontakRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/articles': typeof AdminArticlesRouteRouteWithChildren
  '/admin/models': typeof AdminModelsRouteRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/kontak': typeof AdminKontakRoute
  '/info-promo/$slug': typeof InfoPromoSlugRoute
  '/tipe-mobil/$model': typeof TipeMobilModelRoute
  '/admin/': typeof AdminIndexRoute
  '/info-promo/': typeof InfoPromoIndexRoute
  '/tipe-mobil/': typeof TipeMobilIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/models/$id': typeof AdminModelsIdRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/models/': typeof AdminModelsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/info-promo'
    | '/tipe-mobile'
    | ''
    | '/deferred'
    | '/kontak'
    | '/sign-in'
    | '/sign-up'
    | '/admin/articles'
    | '/admin/models'
    | '/admin/contact-info'
    | '/admin/homepage'
    | '/admin/kontak'
    | '/info-promo/$slug'
    | '/tipe-mobil/$model'
    | '/admin/'
    | '/info-promo/'
    | '/tipe-mobil'
    | '/route-a'
    | '/route-b'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/models/$id'
    | '/admin/articles/'
    | '/admin/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tipe-mobile'
    | ''
    | '/deferred'
    | '/kontak'
    | '/sign-in'
    | '/sign-up'
    | '/admin/contact-info'
    | '/admin/homepage'
    | '/admin/kontak'
    | '/info-promo/$slug'
    | '/tipe-mobil/$model'
    | '/admin'
    | '/info-promo'
    | '/tipe-mobil'
    | '/route-a'
    | '/route-b'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/models/$id'
    | '/admin/articles'
    | '/admin/models'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/info-promo'
    | '/tipe-mobile'
    | '/_pathlessLayout'
    | '/deferred'
    | '/kontak'
    | '/sign-in'
    | '/sign-up'
    | '/admin/articles'
    | '/admin/models'
    | '/_pathlessLayout/_nested-layout'
    | '/admin/contact-info'
    | '/admin/homepage'
    | '/admin/kontak'
    | '/info-promo/$slug'
    | '/tipe-mobil/$model'
    | '/admin/'
    | '/info-promo/'
    | '/tipe-mobil/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/models/$id'
    | '/admin/articles/'
    | '/admin/models/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  InfoPromoRouteRoute: typeof InfoPromoRouteRouteWithChildren
  TipeMobileRouteRoute: typeof TipeMobileRouteRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  KontakRoute: typeof KontakRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TipeMobilModelRoute: typeof TipeMobilModelRoute
  TipeMobilIndexRoute: typeof TipeMobilIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  InfoPromoRouteRoute: InfoPromoRouteRouteWithChildren,
  TipeMobileRouteRoute: TipeMobileRouteRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  DeferredRoute: DeferredRoute,
  KontakRoute: KontakRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TipeMobilModelRoute: TipeMobilModelRoute,
  TipeMobilIndexRoute: TipeMobilIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/info-promo",
        "/tipe-mobile",
        "/_pathlessLayout",
        "/deferred",
        "/kontak",
        "/sign-in",
        "/sign-up",
        "/tipe-mobil/$model",
        "/tipe-mobil/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin.route.tsx",
      "children": [
        "/admin/articles",
        "/admin/models",
        "/admin/contact-info",
        "/admin/homepage",
        "/admin/kontak",
        "/admin/"
      ]
    },
    "/info-promo": {
      "filePath": "info-promo.route.tsx",
      "children": [
        "/info-promo/$slug",
        "/info-promo/"
      ]
    },
    "/tipe-mobile": {
      "filePath": "tipe-mobile.route.tsx"
    },
    "/_pathlessLayout": {
      "filePath": "_pathlessLayout.tsx",
      "children": [
        "/_pathlessLayout/_nested-layout"
      ]
    },
    "/deferred": {
      "filePath": "deferred.tsx"
    },
    "/kontak": {
      "filePath": "kontak.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/admin/articles": {
      "filePath": "admin.articles.route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/articles/$id",
        "/admin/articles/new",
        "/admin/articles/"
      ]
    },
    "/admin/models": {
      "filePath": "admin.models.route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/models/$id",
        "/admin/models/"
      ]
    },
    "/_pathlessLayout/_nested-layout": {
      "filePath": "_pathlessLayout/_nested-layout.tsx",
      "parent": "/_pathlessLayout",
      "children": [
        "/_pathlessLayout/_nested-layout/route-a",
        "/_pathlessLayout/_nested-layout/route-b"
      ]
    },
    "/admin/contact-info": {
      "filePath": "admin.contact-info.tsx",
      "parent": "/admin"
    },
    "/admin/homepage": {
      "filePath": "admin.homepage.tsx",
      "parent": "/admin"
    },
    "/admin/kontak": {
      "filePath": "admin.kontak.tsx",
      "parent": "/admin"
    },
    "/info-promo/$slug": {
      "filePath": "info-promo.$slug.tsx",
      "parent": "/info-promo"
    },
    "/tipe-mobil/$model": {
      "filePath": "tipe-mobil.$model.tsx"
    },
    "/admin/": {
      "filePath": "admin.index.tsx",
      "parent": "/admin"
    },
    "/info-promo/": {
      "filePath": "info-promo.index.tsx",
      "parent": "/info-promo"
    },
    "/tipe-mobil/": {
      "filePath": "tipe-mobil.index.tsx"
    },
    "/_pathlessLayout/_nested-layout/route-a": {
      "filePath": "_pathlessLayout/_nested-layout/route-a.tsx",
      "parent": "/_pathlessLayout/_nested-layout"
    },
    "/_pathlessLayout/_nested-layout/route-b": {
      "filePath": "_pathlessLayout/_nested-layout/route-b.tsx",
      "parent": "/_pathlessLayout/_nested-layout"
    },
    "/admin/articles/$id": {
      "filePath": "admin.articles.$id.tsx",
      "parent": "/admin/articles"
    },
    "/admin/articles/new": {
      "filePath": "admin.articles.new.tsx",
      "parent": "/admin/articles"
    },
    "/admin/models/$id": {
      "filePath": "admin.models.$id.tsx",
      "parent": "/admin/models"
    },
    "/admin/articles/": {
      "filePath": "admin.articles.index.tsx",
      "parent": "/admin/articles"
    },
    "/admin/models/": {
      "filePath": "admin.models.index.tsx",
      "parent": "/admin/models"
    }
  }
}
ROUTE_MANIFEST_END */
