import { RouterProvider, createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen"; // This file is generated by the TanStack Router plugin

// Create router from the file-based route tree
export const router = createRouter({
  routeTree,
  defaultPreload: "intent",
});

// Declare the router provider
export function Router() {
  return <RouterProvider router={router} />;
}

export default Router;
